# Generated by Django 3.2.9 on 2022-06-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='color_image',
            field=models.ImageField(null=True, upload_to='color_img/'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='depth_image',
            field=models.ImageField(null=True, upload_to='depth_img/'),
        ),
    ]
